<?php

class table_info
{
    public static function get_table_info()
    {
        $table_info = array(
            "learn:学习内容" => array(
                "title" => array(
                    "des" => "标题",
                    "columnProperty" => "varchar(1000)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "cover" => array(
                    "des" => "封面图片",
                    "columnProperty" => "varchar(100)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "images" => array(
                    "des" => "图片url",
                    "columnProperty" => "varchar(2000)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "des" => array(
                    "des" => "描述",
                    "columnProperty" => "varchar(2000)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "content" => array(
                    "des" => "内容",
                    "columnProperty" => "varchar(40)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "tag" => array(
                    "des" => "标签",
                    "columnProperty" => "varchar(40)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "project_id" => array(
                    "des" => "关联项目id",
                    "columnProperty" => "int",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "user_id" => array(
                    "des" => "关联用户id",
                    "columnProperty" => "int",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "star" => array(
                    "des" => "点赞数",
                    "columnProperty" => "int",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "see" => array(
                    "des" => "查看数",
                    "columnProperty" => "int",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "commit" => array(
                    "des" => "评论数",
                    "columnProperty" => "int",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
            ),
        );

        ///////////////// 基础表 //////////////////
        $basic_array = array(
            'admin_user:管理后台用户' => array(
                "name" => array(
                    "des" => "后台管理登录用户",
                    "columnProperty" => "varchar(100) unique",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "nick_name" => array(
                    "des" => "后台管理用户名称",
                    "columnProperty" => "varchar(200)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "open_id" => array(
                    "des" => "小程序账号唯一id",
                    "columnProperty" => "varchar(200)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "mobile" => array(
                    "des" => "小程序用户手机号",
                    "columnProperty" => "int",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "cover" => array(
                    "des" => "头像",
                    "columnProperty" => "varchar(200)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "city_name" => array(
                    "des" => "城市",
                    "columnProperty" => "varchar(200)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "address" => array(
                    "des" => "地址",
                    "columnProperty" => "varchar(200)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "ip_address" => array(
                    "des" => "IP地址",
                    "columnProperty" => "varchar(100)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "admin_token" => array(
                    "des" => "后台管理用户token",
                    "columnProperty" => "varchar(200)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "api_token" => array(
                    "des" => "api用户token",
                    "columnProperty" => "varchar(200)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "email" => array(
                    "des" => "用户邮箱",
                    "columnProperty" => "varchar(200)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "role_id" => array(
                    "des" => "用户角色id",
                    "columnProperty" => "int",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "area_id" => array(
                    "des" => "用户区域id",
                    "columnProperty" => "int",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "province_code" => array(
                    "des" => "对应的省code",
                    "columnProperty" => "int",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "city_code" => array(
                    "des" => "对应的城市code",
                    "columnProperty" => "int",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "section_code" => array(
                    "des" => "对应的区域code",
                    "columnProperty" => "int",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "password" => array(
                    "des" => "密码",
                    "columnProperty" => "varchar(40)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "share" => array(
                    "des" => "小程序用户分享信息",
                    "columnProperty" => "int",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "sex" => array(
                    "des" => "小程序用户性别",
                    "columnProperty" => "int",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),                
            ),
            'role:用户角色' => array(
                "name" => array(
                    "des" => "角色名称",
                    "columnProperty" => "varchar(40)",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "edit_admin_user" => array(
                    "des" => "是否可以编辑管理后台用户",
                    "columnProperty" => "tinyint",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "edit_mp_user" => array(
                    "des" => "是否可以编辑小程序用户",
                    "columnProperty" => "tinyint",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "edit_role" => array(
                    "des" => "是否可以编辑用户角色",
                    "columnProperty" => "tinyint",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
                "edit_area" => array(
                    "des" => "是否可以编辑用户区域",
                    "columnProperty" => "tinyint",
                    "sort" => "up",
                    "align" => "left",
                    "fixed" => "right",
                    "width" => 100,
                    "showInSearch" => true,
                    "formType" => "text",
                    "required" => true,
                ),
            ),
        );

        return array_merge($table_info, $basic_array);
    }

    public static function get_table_data()
    {
        $data_info = [
            // 用户基本信息
            "admin_user" => array(
                "name" => "root",
                "nick_name" => "root",
                "password" => "e10adc3949ba59abbe56e057f20f883e",
            ),
            "admin_user" => array(
                "name" => "admin",
                "nick_name" => "admin",
                "password" => "e10adc3949ba59abbe56e057f20f883e",
            ),
            "role" => array(
                "name" => "管理员",
                "edit_admin_user" => 1,
                "edit_mp_user" => 1,
                "edit_role" => 1,
            ),
            "role" => array(
                "name" => "普通用户",
                "edit_admin_user" => 0,
                "edit_mp_user" => 0,
                "edit_role" => 0,
            ),
        ];

        return $data_info;
    }
}
